import assert from 'node:assert/strict'
import { readFile, readdir } from 'node:fs/promises'
import { join } from 'node:path'
import { describe, it } from 'node:test'
import { fileURLToPath } from 'node:url'

const root = fileURLToPath(new URL('..', import.meta.url))

async function text(relative) {
  return readFile(join(root, relative), 'utf8')
}

async function json(relative) {
  return JSON.parse(await text(relative))
}

describe('the package DeepSeek Harness installs from the repository', () => {
  it('declares the bundle patch, the entry point and the locale files', async () => {
    const manifest = await json('package.json')
    assert.equal(manifest.type, 'module')
    assert.equal(manifest.main, 'lib/index.js')
    assert.deepEqual(manifest.dsh, { bundle: { patch: './cordis.patch.yml' } })
    assert.equal(manifest.exports['.'], './lib/index.js')
    assert.equal(manifest.exports['./cordis.patch.yml'], './cordis.patch.yml')
    assert.equal(manifest.exports['./locale/*.json'], './locale/*.json')
    assert.equal(typeof manifest.description, 'string')
    assert.ok(manifest.description.length > 10)
  })

  it('declares the host packages as peers and as development dependencies', async () => {
    const manifest = await json('package.json')
    for (const hostPackage of ['@deepseek-ai/cordis', '@deepseek-ai/dsh-tools', '@deepseek-ai/schemastery']) {
      assert.equal(typeof manifest.peerDependencies[hostPackage], 'string', hostPackage)
      assert.equal(typeof manifest.devDependencies[hostPackage], 'string', hostPackage)
    }
  })

  it('ships the compiled plugin, not only its sources', async () => {
    const files = await readdir(join(root, 'lib'))
    assert.ok(files.includes('index.js'))
    assert.ok(files.includes('cited.js'))
    const compiled = await text('lib/index.js')
    assert.match(compiled, /^\/\/ Generated by scripts\/build\.mjs from src\/index\.js/)
  })

  it('publishes every path the manifest declares, and none of the sources', async () => {
    const manifest = await json('package.json')
    for (const entry of ['lib', 'cordis.patch.yml', 'README.md', 'README.es.md', 'README.zh.md', 'LICENSE', 'NOTICE']) {
      assert.ok(manifest.files.includes(entry), entry)
    }
    assert.ok(manifest.files.includes('locale/*.json'))
    assert.equal(manifest.files.some((entry) => entry.startsWith('src') || entry.startsWith('tests')), false)
    for (const entry of ['lib/index.js', 'lib/cited.js', 'cordis.patch.yml', 'LICENSE', 'NOTICE']) await text(entry)
  })

  it('inserts one row whose id differs from the package name', async () => {
    const patch = await text('cordis.patch.yml')
    const ids = [...patch.matchAll(/^\s*- id: (.+)$/gm)].map((match) => match[1].trim())
    const names = [...patch.matchAll(/^\s*name: '(.+)'$/gm)].map((match) => match[1].trim())
    assert.deepEqual(ids, ['cited'])
    assert.deepEqual(names, ['dsh-cited'])
    assert.notEqual(ids[0], names[0])
  })

  it('carries the card of the plugin in English, Chinese and Spanish', async () => {
    for (const locale of ['en', 'zh', 'es']) {
      const catalog = await json(`locale/${locale}.json`)
      assert.equal(catalog.meta.title, 'Cited', locale)
      assert.equal(typeof catalog.meta.description, 'string', locale)
      assert.ok(catalog.meta.description.length > 10, locale)
    }
  })

  it('keeps the license and the notice of Katalis', async () => {
    const license = await text('LICENSE')
    assert.match(license, /Apache License/)
    const notice = await text('NOTICE')
    assert.match(notice, /Built by Katalis/)
  })

  it('documents the installation in the README, in English and in Spanish', async () => {
    const readme = await text('README.md')
    assert.match(readme, /github:RonnieGex\/dsh-cited/)
    assert.match(await text('README.es.md'), /RonnieGex\/dsh-cited/)
    assert.match(await text('README.zh.md'), /RonnieGex\/dsh-cited/)
  })
})
