import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = fileURLToPath(new URL('..', import.meta.url))
const sourceDir = join(root, 'src')
const outputDir = join(root, 'lib')
const check = process.argv.includes('--check')

async function compiled() {
  const files = (await readdir(sourceDir)).filter((file) => file.endsWith('.js')).sort()
  const output = new Map()
  for (const file of files) {
    const source = (await readFile(join(sourceDir, file), 'utf8')).replace(/\r\n/g, '\n')
    const body = source.endsWith('\n') ? source : `${source}\n`
    output.set(file, `// Generated by scripts/build.mjs from src/${file} — do not edit this file directly.\n${body}`)
  }
  return output
}

if (check) {
  const expected = await compiled()
  const problems = []
  let actual = []
  try {
    actual = (await readdir(outputDir)).filter((file) => file.endsWith('.js')).sort()
  } catch {
    problems.push('lib/ does not exist')
  }
  for (const file of expected.keys()) {
    if (actual.includes(file) === false) {
      problems.push(`lib/${file} is missing`)
      continue
    }
    const shipped = (await readFile(join(outputDir, file), 'utf8')).replace(/\r\n/g, '\n')
    if (shipped !== expected.get(file)) problems.push(`lib/${file} differs from the regenerated file`)
  }
  for (const file of actual) {
    if (expected.has(file) === false) problems.push(`lib/${file} has no source in src/`)
  }
  if (problems.length > 0) {
    for (const problem of problems) console.log(`BUILD: RED ${problem}`)
    process.exit(1)
  }
  console.log(`BUILD: GREEN ${expected.size} file(s) match src/`)
} else {
  await rm(outputDir, { recursive: true, force: true })
  await mkdir(outputDir, { recursive: true })
  const expected = await compiled()
  for (const [file, content] of expected) await writeFile(join(outputDir, file), content, 'utf8')
  console.log(`BUILD: wrote ${expected.size} file(s) to lib/`)
}
